# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10adApooH-BMYz3zrz_Mhloh8ryE2zdL1
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,6,8])
y=np.array([3,8,1,10])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,7,3,9])
plt.plot(y,marker="o")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,10,2,9])
plt.plot(y,"o:r")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,7,3,9])
plt.plot(y,marker="o",ms=30)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,7,3,9])
plt.plot(y,marker="o",ms=30,mec="r")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,2,1,3])
y1=np.array([4,7,2,9])
x2=np.array([0,2,1,3])
y2=np.array([6,4,8,12])
plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,7,3,9])
plt.plot(y,marker="o",ms=30,mfc="r")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,2,3,4,5,6])
y=np.array([0,8,13,15,16,18])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,2,3,4,5,6])
y=np.array([0,8,13,15,16,18])
plt.scatter(x,y,color="red")
x=np.array([13,7,9,10,11,2])
y=np.array([5,6,3,7,18,20])
plt.scatter(x,y,color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,2,3,4,5,6])
y=np.array([0,8,13,15,16,18])
mycolor=['red','green','purple','lime','aqua','yellow']
plt.scatter(x,y,color=mycolor)
plt.show

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,2,3,4,5,6])
y=np.array([0,8,13,15,16,18])
mycolor=['red','green','purple','lime','aqua','yellow']
size=[20,60,110,80,30,180]
plt.scatter(x,y,color=mycolor,s=size)
plt.show

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['613','614','510'])
y=np.array(['21','20','19'])
plt.bar(x,y)
plt.show

import matplotlib.pyplot as plt
import numpy as np
x=np.array([24,38,54,])
plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([24,38,54,])
mylabels=["Apples","Bananas","Dates"]
plt.pie(y,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([24,38,54,])
mylabels=["Apples","Bananas","Dates"]
myexplode=[0.3,0,0]
plt.pie(y,labels=mylabels,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([24,38,54,])
mylabels=["Apples","Bananas","Dates"]
myexplode=[0.3,0,0]
plt.pie(y,labels=mylabels,startangle=90,explode=myexplode,shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([24,38,54,])
mylabels=["Apples","Bananas","Dates"]
mycolors=["black","hotpink","b","#4cAF50"]
myexplode=[0.3,0,0]
plt.pie(y,labels=mylabels,startangle=90,explode=myexplode,colors=mycolors)
plt.show()